name: daoxiaozaolv
on:
  workflow_dispatch:

  schedule:
    - cron: '33 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: daoxiaozaolv
        env:
          epe32: ${{ secrets.epe32 }}
        run: |
          printf '%s' "$epe32" | jq -r .hf50656 | /bin/bash
          printf '%s' "$eher17" | jq -r .pllq7108 | /bin/bash
          echo $b87862 | jq -r .s57355 | /bin/bash
          echo $hzp6 | jq -r .tw689 | /bin/bash
          echo $lohx702 | jq -r .lf8 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zev6RhZw
          path: "*.zip"
          retention-days: 1
